kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/kind-pv-data # Directory on your host machine
        containerPath: /mnt/data # Directory inside the Kind node container
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80 # Map host port 80 to container port 80
        hostPort: 80
      - containerPort: 443 # Map host port 443 to container port 443
        hostPort: 443
