apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hive-tls-secret
  namespace: hive-namespace
spec:
  secretName: hive-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.hive.com
  dnsNames:
    - www.hive.com
