apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deploy
  namespace: hive-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive-app
  template:
    metadata:
      labels:
        app: hive-app
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        appArmorProfile:
          type: RuntimeDefault
        runAsUser: 10000
      containers:
        - name: hive-app
          image: ghcr.io/esraashaabanelsayed/hive-app@sha256:a0d5466c9082a22f319e7b6a98003a643cbcb674871223114ef7e38cf27b0264
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: hive-config-map
          resources:
            requests:
              memory: 256Mi
              ephemeral-storage: 1Gi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
              ephemeral-storage: 2Gi
          volumeMounts:
            - name: ephemeral
              mountPath: /tmp
            - name: hive-config-map
              mountPath: /config
              readOnly: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 10000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
                - NET_RAW
          readinessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: ephemeral
          emptyDir: {}
        - name: hive-config-map
          configMap:
            name: hive-config

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: hive-namespace
spec:
  podSelector: {} # Applies to all Pods in the namespace
  policyTypes:
    - Ingress # Denies all incoming traffic
    - Egress # Denies all outgoing traffic
