apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: hive-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: www.hive.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hive-svc
                port:
                  number: 5000
