name: CI_workflow
on: push
jobs:
   
    linting_job:
        runs-on : ubuntu-24.04
        permissions:
              contents: read
              packages: read
              # To report GitHub Actions status checks
              statuses: write
        
        steps: 
          - name: checkout step
            uses: actions/checkout@v4
            with:
          # super-linter needs the full git history to get the list of files that changed across commits
              fetch-depth: 0
          - name: Super-linter
            uses: super-linter/super-linter@v7.2.1 
            env:
                # To report GitHub Actions status checks
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            



    build_docker_image:
        runs-on : ubuntu-24.04
        steps: 
           - name: checkout step
             uses: actions/checkout@v4

           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v3

           - name: Build 
             uses: docker/build-push-action@v6
             with:
                push: false
                
      


    # unit_testing_job:
    #     runs-on : ubuntu_latest
    #     steps: 
    #       - name: checkout step
    #         uses: actions/checkout@v4




